### ISSUE TITLE
ProductiveRage.ReactRouting not building into output JS

### ISSUE THREAD

**Issue by Porl91** [ProductiveRage/Bridge.ReactRouting#1]
If I create an empty project with just a definition for a Navigator I receive a JS error in the developer tools, suggesting that the ProductiveRage.ReactRouting package isn't being built into the output:

```
public sealed class TestNavigator : Navigator
{
    public TestNavigator(Set<NonBlankTrimmedString> parentSegments, 
        IInteractWithBrowserRouting historyHandler, 
        AppDispatcher dispatcher)
        : base(parentSegments, historyHandler, dispatcher)
    {
    }
}
```

The error:
Uncaught TypeError: Cannot read property 'Navigator' of undefined
![hh](https://cloud.githubusercontent.com/assets/13272784/19040884/d68302dc-897d-11e6-83d6-06e5371c05d7.jpg)

If this isn't a bug, perhaps it's to do with the version I'm using being incompatible with Bridge, so here are the Nugets I have installed in this test project:
![hhh](https://cloud.githubusercontent.com/assets/13272784/19040915/fc865fba-897d-11e6-84fd-dd426539668e.jpg)

**Comment by ProductiveRage** [comment]
I've reproduced the issue with a clean solution. Looking at the ProductiveRage.ReactRouting.dll binary, the resource that contains the JavaScript is absent. I'm not sure how that happened, hopefully it's an easy fix.

**Comment by ProductiveRage** [comment]
This has been fixed. The latest version (available now in NuGet) has binaries that include the JS resource.
